version: "3.7"

services:
  server:
    image: homeassistant/home-assistant:2022.7.6@sha256:f4ce55e5d7dd0a54ba38cf87bb671e78d3bcc93d1a5f5f40bc87aab10eb2fc0b
    network_mode: host
    container_name: home-assistant
    restart: unless-stopped
    volumes:
      # run export APP_DATA_DIR="$(pwd)"
      - /home/umbrel/home-assistant/data:/config
      # Until this is fixed: https://github.com/zigpy/zha-device-handlers/issues/1306
      - /home/umbrel/home-assistant/deps/zhaquirks/yooksmart:/usr/local/lib/python3.10/site-packages/zhaquirks/yooksmart
      - /home/umbrel/home-assistant/deps/zhaquirks/tuya/ts110e.py:/usr/local/lib/python3.10/site-packages/zhaquirks/tuya/ts110e.py
      - /home/umbrel/home-assistant/deps/mega:/usr/local/lib/python3.10/site-packages/mega
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_f8e102a854d9eb11bc15148e6fe9f4d9-if00-port0:/dev/sonoff'
